### PR TITLE
Try again to fix CORS error

### LINKED ISSUE #18: Access to REST api blocked by CORS policy
```
Access to fetch at 'https://matrixdev.xyz/api/v1/oauth/details' from origin 'https://www.matrixdev.xyz' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

Failed to load resource: net::ERR_FAILED
www.matrixdev.xyz/:1 Access to fetch at 'https://matrixdev.xyz/api/v1/get/server/755687537753718815' from origin 'https://www.matrixdev.xyz' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

matrixdev.xyz/api/v1/get/server/755687537753718815:1 Failed to load resource: net::ERR_FAILED
```
REST api is still being unable to be fetched, so incorrect statistics is being displayed.
Login system also does not display the user's username after they have logged in.

### PR DESCRIPTION
**Pull request by Lucaslah**
Should fix the error: 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://matrixdev.xyz/api/v1/oauth/details. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

### CODE REVIEW

**Comment by 6xtvo** [comment]
Looks good.

**Comment by 6xtvo** [comment]
Don't think anything has changed.
1) Data is still not being fetched from API
2) Login doesn't work (username isn't displayed)
image

**Comment by Lucaslah** [comment]
> Don't think anything has changed.
> 
>     1. Data is still not being fetched from API
> 
>     2. Login doesn't work (username isn't displayed)
>        image

The data is being fetched but cors is blocking it

**Comment by 6xtvo** [comment]
> > Don't think anything has changed.
> > ```
> > 1. Data is still not being fetched from API
> > 
> > 2. Login doesn't work (username isn't displayed)
> >    image
> > ```
> 
> The data is being fetched but cors is blocking it

That's what I meant.

**Pull request merged**
